var actions = [{
  "id": 1,
  "name": "amet diam in magna bibendum imperdiet nullam",
  "complete": 40,
  "start_date": "5/11/2015",
  "finish_date": "10/31/2015",
  "duration": "2h",
  "type": "Contact",
  "status": "Active",
  "main_contact": "John A.",
  "managed_by": "David W.",
  "assigned_to": "David W.",
  "client_access": "View",
  "priority": "Low",
  "billable_time": "No",
  "details": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
  "created": "2014-11-29 03:23:37",
  "modified": "2015-08-29 09:56:49",
  "activity": "2015-07-14 06:40:53",
  "project_name": "Project 3",
  "score": 85
}, {
  "id": 2,
  "name": "at nunc",
  "complete": 70,
  "start_date": "2/6/2015",
  "finish_date": "12/6/2015",
  "duration": "4h",
  "type": "Tweak",
  "status": "Cancel",
  "main_contact": "Sue A.",
  "managed_by": "David H.",
  "assigned_to": "Dezmond F.",
  "client_access": "View",
  "priority": "High",
  "billable_time": "Yes",
  "details": "Fusce consequat. Nulla nisl. Nunc nisl.",
  "notes": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
  "created": "2015-03-09 11:32:56",
  "modified": "2015-08-29 01:16:48",
  "activity": "2015-05-05 07:11:08",
  "project_name": "Project 3",
  "score": 77
}, {
  "id": 3,
  "name": "etiam faucibus cursus urna ut tellus nulla ut erat id",
  "complete": 70,
  "start_date": "3/9/2015",
  "finish_date": "11/24/2015",
  "duration": "1h",
  "type": "Contact",
  "status": "Cancel",
  "main_contact": "Sue A.",
  "managed_by": "David W.",
  "assigned_to": "Dezmond F.",
  "client_access": "Hidden",
  "priority": "Low",
  "billable_time": "Yes",
  "details": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
  "notes": "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
  "created": "2015-04-05 23:37:59",
  "modified": "2015-04-11 22:43:48",
  "activity": "2014-11-19 11:33:43",
  "project_name": "Project 3",
  "score": 58
}, {
  "id": 4,
  "name": "vel nisl duis ac nibh fusce lacus purus",
  "complete": 58,
  "start_date": "5/3/2015",
  "finish_date": "10/10/2015",
  "duration": "3h",
  "type": "Tweak",
  "status": "Review",
  "main_contact": "Sue A.",
  "managed_by": "Dezmond F.",
  "assigned_to": "Dezmond F.",
  "client_access": "Hidden",
  "priority": "Low",
  "billable_time": "No",
  "details": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
  "notes": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
  "created": "2015-06-06 11:17:24",
  "modified": "2015-05-22 04:50:56",
  "activity": "2015-08-05 17:18:20",
  "project_name": "Project 3",
  "score": 42
}, {
  "id": 5,
  "name": "varius nulla facilisi cras non velit",
  "complete": 96,
  "start_date": "4/29/2015",
  "finish_date": "11/25/2015",
  "duration": "3h",
  "type": "Development",
  "status": "Cancel",
  "main_contact": "Sue A.",
  "managed_by": "David H.",
  "assigned_to": "Dezmond F.",
  "client_access": "Modify",
  "priority": "Med",
  "billable_time": "No",
  "details": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
  "notes": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
  "created": "2015-03-07 23:26:45",
  "modified": "2015-08-18 17:46:59",
  "activity": "2015-06-15 04:23:35",
  "project_name": "Project 2",
  "score": 67
}, {
  "id": 6,
  "name": "convallis nunc proin at turpis",
  "complete": 62,
  "start_date": "11/23/2014",
  "finish_date": "11/12/2015",
  "duration": "3h",
  "type": "Research",
  "status": "Active",
  "main_contact": "Sue A.",
  "managed_by": "Dezmond F.",
  "assigned_to": "David H.",
  "client_access": "Hidden",
  "priority": "Low",
  "billable_time": "Yes",
  "details": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
  "created": "2015-03-24 04:36:35",
  "modified": "2015-08-31 05:05:38",
  "activity": "2014-11-03 08:44:41",
  "project_name": "Project 6",
  "score": 19
}, {
  "id": 7,
  "name": "mauris eget massa",
  "complete": 5,
  "start_date": "4/3/2015",
  "finish_date": "11/12/2015",
  "duration": "4h",
  "type": "Planning",
  "status": "Cancel",
  "main_contact": "William H.",
  "managed_by": "David H.",
  "assigned_to": "David W.",
  "client_access": "Hidden",
  "priority": "High",
  "billable_time": "No",
  "details": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
  "created": "2014-10-16 08:33:32",
  "modified": "2015-09-20 03:57:18",
  "activity": "2015-02-24 10:59:36",
  "project_name": "Project 5",
  "score": 92
}, {
  "id": 8,
  "name": "lorem quisque ut erat curabitur gravida nisi at",
  "complete": 41,
  "start_date": "11/25/2014",
  "finish_date": "11/19/2015",
  "duration": "2h",
  "type": "Contact",
  "status": "Review",
  "main_contact": "William H.",
  "managed_by": "David H.",
  "assigned_to": "David H.",
  "client_access": "Modify",
  "priority": "High",
  "billable_time": "No",
  "notes": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
  "created": "2015-10-04 10:13:02",
  "modified": "2014-10-27 16:51:50",
  "activity": "2015-07-13 23:00:10",
  "project_name": "Project 4",
  "score": 25
}, {
  "id": 9,
  "name": "ut massa volutpat convallis morbi odio odio elementum eu",
  "complete": 38,
  "start_date": "7/11/2015",
  "finish_date": "10/31/2015",
  "duration": "1h",
  "type": "Development",
  "status": "Review",
  "main_contact": "William H.",
  "managed_by": "David H.",
  "assigned_to": "Dezmond F.",
  "client_access": "Hidden",
  "priority": "Low",
  "billable_time": "Yes",
  "details": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
  "notes": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
  "created": "2015-09-13 12:19:02",
  "modified": "2014-10-09 04:57:36",
  "activity": "2015-06-04 07:58:15",
  "project_name": "Project 1",
  "score": 96
}, {
  "id": 10,
  "name": "odio curabitur convallis",
  "complete": 68,
  "start_date": "7/23/2015",
  "finish_date": "10/26/2015",
  "duration": "3h",
  "type": "Development",
  "status": "Progress",
  "main_contact": "John A.",
  "managed_by": "David H.",
  "assigned_to": "David H.",
  "client_access": "Inherit",
  "priority": "Low",
  "billable_time": "No",
  "details": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
  "notes": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
  "created": "2015-02-04 11:34:35",
  "modified": "2015-06-17 07:09:42",
  "activity": "2015-06-13 10:24:49",
  "project_name": "Project 1",
  "score": 97
}, {
  "id": 11,
  "name": "sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum",
  "complete": 16,
  "start_date": "2/1/2015",
  "finish_date": "10/26/2015",
  "duration": "1h",
  "type": "Research",
  "status": "Progress",
  "main_contact": "Dustin H.",
  "managed_by": "David H.",
  "assigned_to": "David W.",
  "client_access": "View",
  "priority": "Low",
  "billable_time": "No",
  "details": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
  "notes": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
  "created": "2015-09-08 09:44:52",
  "modified": "2014-10-12 05:51:09",
  "activity": "2014-11-05 20:21:01",
  "project_name": "Project 2",
  "score": 53
}, {
  "id": 12,
  "name": "rhoncus aliquam lacus morbi quis tortor id nulla",
  "complete": 37,
  "start_date": "8/15/2015",
  "finish_date": "11/28/2015",
  "duration": "4h",
  "type": "Bugfix",
  "status": "Review",
  "main_contact": "John A.",
  "managed_by": "David W.",
  "assigned_to": "Dezmond F.",
  "client_access": "Hidden",
  "priority": "Med",
  "billable_time": "No",
  "details": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
  "created": "2014-10-18 05:59:15",
  "modified": "2015-02-17 03:30:51",
  "activity": "2014-11-08 04:39:23",
  "project_name": "Project 6",
  "score": 94
}, {
  "id": 13,
  "name": "posuere cubilia curae duis faucibus",
  "complete": 32,
  "start_date": "2/12/2015",
  "finish_date": "10/23/2015",
  "duration": "1h",
  "type": "Bugfix",
  "status": "Active",
  "main_contact": "John A.",
  "managed_by": "Dezmond F.",
  "assigned_to": "David H.",
  "client_access": "Modify",
  "priority": "Med",
  "billable_time": "Yes",
  "details": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
  "notes": "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  "created": "2014-11-12 20:50:47",
  "modified": "2015-05-28 23:08:02",
  "activity": "2015-09-02 15:33:40",
  "project_name": "Project 5",
  "score": 27
}, {
  "id": 14,
  "name": "nulla suscipit ligula in lacus curabitur at",
  "complete": 78,
  "start_date": "1/29/2015",
  "finish_date": "12/4/2015",
  "duration": "2h",
  "type": "Bugfix",
  "status": "Complete",
  "main_contact": "Dustin H.",
  "managed_by": "Dezmond F.",
  "assigned_to": "David W.",
  "client_access": "Hidden",
  "priority": "Low",
  "billable_time": "No",
  "notes": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
  "created": "2015-02-21 03:50:08",
  "modified": "2015-01-30 05:16:58",
  "activity": "2014-11-19 02:45:45",
  "project_name": "Project 2",
  "score": 39
}, {
  "id": 15,
  "name": "praesent blandit lacinia erat vestibulum",
  "complete": 7,
  "start_date": "6/13/2015",
  "finish_date": "11/17/2015",
  "duration": "2h",
  "type": "Planning",
  "status": "Cancel",
  "main_contact": "John A.",
  "managed_by": "David H.",
  "assigned_to": "David W.",
  "client_access": "View",
  "priority": "Med",
  "billable_time": "Yes",
  "details": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
  "notes": "In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
  "created": "2015-09-28 01:05:12",
  "modified": "2015-06-06 03:39:07",
  "activity": "2015-08-08 06:48:29",
  "project_name": "Project 5",
  "score": 9
}, {
  "id": 16,
  "name": "sagittis sapien",
  "complete": 90,
  "start_date": "5/19/2015",
  "finish_date": "10/26/2015",
  "duration": "2h",
  "type": "Research",
  "status": "Progress",
  "main_contact": "Sue A.",
  "managed_by": "David W.",
  "assigned_to": "David W.",
  "client_access": "Inherit",
  "priority": "High",
  "billable_time": "No",
  "details": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
  "notes": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
  "created": "2015-03-30 22:50:30",
  "modified": "2015-04-23 03:39:32",
  "activity": "2014-11-14 17:35:30",
  "project_name": "Project 5",
  "score": 76
}, {
  "id": 17,
  "name": "potenti in",
  "complete": 66,
  "start_date": "2/12/2015",
  "finish_date": "11/16/2015",
  "duration": "1h",
  "type": "Bugfix",
  "status": "Active",
  "main_contact": "William H.",
  "managed_by": "David W.",
  "assigned_to": "David W.",
  "client_access": "View",
  "priority": "Med",
  "billable_time": "No",
  "details": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
  "notes": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  "created": "2015-04-22 07:19:31",
  "modified": "2014-11-15 20:59:32",
  "activity": "2015-02-27 01:35:46",
  "project_name": "Project 5",
  "score": 30
}, {
  "id": 18,
  "name": "justo nec condimentum neque sapien placerat ante nulla justo",
  "complete": 25,
  "start_date": "6/10/2015",
  "finish_date": "11/22/2015",
  "duration": "3h",
  "type": "Service",
  "status": "Active",
  "main_contact": "John A.",
  "managed_by": "Dezmond F.",
  "assigned_to": "David H.",
  "client_access": "Inherit",
  "priority": "Low",
  "billable_time": "Yes",
  "notes": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
  "created": "2015-08-21 09:06:29",
  "modified": "2014-10-19 14:52:23",
  "activity": "2015-01-05 05:21:47",
  "project_name": "Project 4",
  "score": 29
}, {
  "id": 19,
  "name": "interdum mauris non ligula pellentesque ultrices phasellus",
  "complete": 60,
  "start_date": "8/23/2015",
  "finish_date": "10/12/2015",
  "duration": "1h",
  "type": "Planning",
  "status": "Active",
  "main_contact": "William H.",
  "managed_by": "Dezmond F.",
  "assigned_to": "David W.",
  "client_access": "Hidden",
  "priority": "High",
  "billable_time": "Yes",
  "details": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
  "notes": "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
  "created": "2015-03-24 15:25:11",
  "modified": "2015-04-17 17:21:39",
  "activity": "2015-09-03 01:43:37",
  "project_name": "Project 2",
  "score": 97
}, {
  "id": 20,
  "name": "parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien",
  "complete": 71,
  "start_date": "5/1/2015",
  "finish_date": "10/14/2015",
  "duration": "3h",
  "type": "Planning",
  "status": "Progress",
  "main_contact": "John A.",
  "managed_by": "Dezmond F.",
  "assigned_to": "David H.",
  "client_access": "Inherit",
  "priority": "Med",
  "billable_time": "No",
  "details": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
  "notes": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
  "created": "2015-01-11 05:20:41",
  "modified": "2015-06-01 10:48:00",
  "activity": "2015-09-15 14:54:02",
  "project_name": "Project 2",
  "score": 80
}, {
  "id": 21,
  "name": "nulla suscipit ligula in lacus curabitur at",
  "complete": 10,
  "start_date": "6/27/2015",
  "finish_date": "10/18/2015",
  "duration": "3h",
  "type": "Tweak",
  "status": "Review",
  "main_contact": "William H.",
  "managed_by": "David W.",
  "assigned_to": "David H.",
  "client_access": "Modify",
  "priority": "Low",
  "billable_time": "No",
  "details": "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
  "notes": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
  "created": "2014-10-23 04:32:57",
  "modified": "2015-03-05 03:47:58",
  "activity": "2014-12-08 09:06:15",
  "project_name": "Project 4",
  "score": 99
}, {
  "id": 22,
  "name": "etiam faucibus cursus urna ut tellus nulla ut erat id",
  "complete": 48,
  "start_date": "12/7/2014",
  "finish_date": "10/27/2015",
  "duration": "2h",
  "type": "Research",
  "status": "Active",
  "main_contact": "John A.",
  "managed_by": "David H.",
  "assigned_to": "David H.",
  "client_access": "Modify",
  "priority": "Low",
  "billable_time": "Yes",
  "details": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
  "notes": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
  "created": "2015-03-13 02:36:10",
  "modified": "2015-01-18 18:01:30",
  "activity": "2015-02-23 13:23:13",
  "project_name": "Project 2",
  "score": 47
}, {
  "id": 23,
  "name": "porttitor lorem id ligula suspendisse ornare consequat",
  "complete": 30,
  "start_date": "8/3/2015",
  "finish_date": "11/1/2015",
  "duration": "1h",
  "type": "Bugfix",
  "status": "Progress",
  "main_contact": "Sue A.",
  "managed_by": "David H.",
  "assigned_to": "David H.",
  "client_access": "View",
  "priority": "Low",
  "billable_time": "Yes",
  "details": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
  "notes": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
  "created": "2015-02-19 21:26:05",
  "modified": "2015-08-19 23:47:58",
  "activity": "2015-06-05 18:55:17",
  "project_name": "Project 3",
  "score": 41
}, {
  "id": 24,
  "name": "ut rhoncus aliquet pulvinar",
  "complete": 73,
  "start_date": "3/8/2015",
  "finish_date": "10/11/2015",
  "duration": "2h",
  "type": "Tweak",
  "status": "Review",
  "main_contact": "William H.",
  "managed_by": "David H.",
  "assigned_to": "David H.",
  "client_access": "Hidden",
  "priority": "Med",
  "billable_time": "No",
  "notes": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
  "created": "2015-05-28 19:40:19",
  "modified": "2015-09-26 17:18:16",
  "activity": "2015-01-14 05:19:57",
  "project_name": "Project 2",
  "score": 58
}, {
  "id": 25,
  "name": "id ornare imperdiet",
  "complete": 76,
  "start_date": "2/10/2015",
  "finish_date": "10/18/2015",
  "duration": "2h",
  "type": "Research",
  "status": "Cancel",
  "main_contact": "William H.",
  "managed_by": "Dezmond F.",
  "assigned_to": "Dezmond F.",
  "client_access": "Inherit",
  "priority": "Low",
  "billable_time": "No",
  "details": "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
  "created": "2015-02-12 03:42:52",
  "modified": "2015-02-17 14:01:58",
  "activity": "2015-02-01 09:55:15",
  "project_name": "Project 3",
  "score": 54
}, {
  "id": 26,
  "name": "orci nullam molestie nibh",
  "complete": 42,
  "start_date": "10/13/2014",
  "finish_date": "10/11/2015",
  "duration": "3h",
  "type": "Service",
  "status": "Progress",
  "main_contact": "Sue A.",
  "managed_by": "Dezmond F.",
  "assigned_to": "Dezmond F.",
  "client_access": "Hidden",
  "priority": "Low",
  "billable_time": "No",
  "created": "2015-05-05 01:31:28",
  "modified": "2015-08-02 10:23:27",
  "activity": "2015-03-19 20:05:51",
  "project_name": "Project 1",
  "score": 50
}, {
  "id": 27,
  "name": "rhoncus",
  "complete": 21,
  "start_date": "8/24/2015",
  "finish_date": "11/12/2015",
  "duration": "4h",
  "type": "Planning",
  "status": "Progress",
  "main_contact": "Dustin H.",
  "managed_by": "David H.",
  "assigned_to": "David H.",
  "client_access": "Inherit",
  "priority": "Low",
  "billable_time": "No",
  "notes": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
  "created": "2015-08-18 18:33:41",
  "modified": "2015-03-03 11:11:21",
  "activity": "2015-05-03 19:39:18",
  "project_name": "Project 6",
  "score": 49
}, {
  "id": 28,
  "name": "at feugiat non pretium quis lectus suspendisse",
  "complete": 13,
  "start_date": "1/28/2015",
  "finish_date": "11/5/2015",
  "duration": "4h",
  "type": "Research",
  "status": "Review",
  "main_contact": "Sue A.",
  "managed_by": "David W.",
  "assigned_to": "David H.",
  "client_access": "Modify",
  "priority": "Med",
  "billable_time": "No",
  "notes": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
  "created": "2015-08-20 00:53:15",
  "modified": "2015-05-05 16:11:03",
  "activity": "2015-05-18 23:16:49",
  "project_name": "Project 6",
  "score": 67
}, {
  "id": 29,
  "name": "interdum eu",
  "complete": 31,
  "start_date": "4/15/2015",
  "finish_date": "11/30/2015",
  "duration": "3h",
  "type": "Research",
  "status": "Cancel",
  "main_contact": "William H.",
  "managed_by": "Dezmond F.",
  "assigned_to": "Dezmond F.",
  "client_access": "Inherit",
  "priority": "Med",
  "billable_time": "Yes",
  "details": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
  "notes": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
  "created": "2015-07-12 22:46:21",
  "modified": "2015-09-18 19:16:43",
  "activity": "2015-02-03 18:49:35",
  "project_name": "Project 1",
  "score": 45
}, {
  "id": 30,
  "name": "sapien urna",
  "complete": 53,
  "start_date": "2/20/2015",
  "finish_date": "11/24/2015",
  "duration": "1h",
  "type": "Bugfix",
  "status": "Cancel",
  "main_contact": "Sue A.",
  "managed_by": "Dezmond F.",
  "assigned_to": "David H.",
  "client_access": "Inherit",
  "priority": "Low",
  "billable_time": "No",
  "details": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  "notes": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
  "created": "2015-02-25 09:24:33",
  "modified": "2015-01-24 02:34:32",
  "activity": "2015-06-28 00:13:16",
  "project_name": "Project 2",
  "score": 24
}];

export default actions;
